### ISSUE TITLE
Damaged .nii output

### ISSUE THREAD

**Issue by hajerkr** [mh-cad/vistarsier#25]
Hello,

just wondering if anyone has encountered this issue before? This is not specific to this subject, but pretty much every output, despite the image running with no issues (apparently)

```
Compared. Mean=449.32097028421146, stdDv=102.17181893856952, size=32143
Compared. Mean=449.32097028421146, stdDv=102.17181893856952, size=32143
Complete:
Initial brain match  : 0.8807195119760403
Union brain match    : 0
Successful           : True
Time to complete     : 00:00:49.9066508

```
Thanks!

![image](https://user-images.githubusercontent.com/13291010/125791645-ffb0c545-6be8-4e85-abef-52cb39bec405.png)

**Comment by plwp** [comment]
Hi, 

I've had a look into this issue and it looks like the output is using the RBG_VECTOR_INTENT field which is meant for GIFTI files.

I'll have a look if there's an easy fix to allow nibabel to read the files but in the meantime the Brainsuite viewer is a lot more forgiving and should be able to view the files.

**Comment by plwp** [comment]
I've changed the dim field in the header which seemed to fix the error. FSLEyes seems to produce a different colour profile than MRIcron (pink instead of orange). 

I've updated the docker image with the new changes.

-Pat

**Comment by hajerkr** [comment]
Hi @plwp , thanks for the update. I pulled the new image but itseems to be having an issue.. ? I am running it the exact same way as yesterday.


```
Unhandled exception. System.AggregateException: One or more errors occurred. (Access to the path '/usr/share/vistarsier/cfg/config.json' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path '/usr/share/vistarsier/cfg/config.json' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at VisTarsier.Config.CapiConfig.GetConfig(String configFilePath) in /root/code/vistarsier/VisTarsier.Config/CapiConfig.cs:line 64
   at VisTarsier.Config.CapiConfig.GetConfig() in /root/code/vistarsier/VisTarsier.Config/CapiConfig.cs:line 41
   at VisTarsier.NiftiLib.Processing.BiasCorrection.AntsN4(String inputFile, DataReceivedEventHandler updates) in /root/code/vistarsier/VisTarsier.NiftiLib/Processing/BiasCorrection.cs:line 47
   at VisTarsier.Module.MS.MSPipeline.<>c__DisplayClass17_0.<Process>b__10() in /root/code/vistarsier/VisTarsier.MS/MSPipeline.cs:line 85
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at VisTarsier.Module.MS.MSPipeline.Process() in /root/code/vistarsier/VisTarsier.MS/MSPipeline.cs:line 89
   at VisTarsier.CommandLineTool.Program.Main(String[] args) in /root/code/vistarsier/VisTarsier.Console/Program.cs:line 43
Aborted
```

**Comment by plwp** [comment]
This may have to do with singularity not running as root. 
Maybe try running with the -f option.

**Comment by hajerkr** [comment]
Thanks @plwp , I tried that, `could not use fakeroot: no mapping entry found `. 
Did something fundamental change in the last update? Because it worked fine before that. Thank you very much for your support with this.

**Comment by plwp** [comment]
I think I just saved the config file as root before building the container, which doesn't affect docker since it uses root for everything within the container but singularity seems inherit permissions from the host.

I've just pushed a new build with updated permissions but if that doesn't work you might have to work out how to run the singularity converted container with elevated privileges.

**Comment by hajerkr** [comment]
Thanks @plwp. Getting a different error after pulling the most recent version. Seems to be an issue with the build weirdly, although the Dockerfile did not change from what I see. The system admin tried with his sudo privileges and still got the same error.

![image](https://user-images.githubusercontent.com/13291010/126347777-632c52c3-2dba-44cc-8df4-9741ea45c041.png)

I am thinking if this is a FSLEyes-specific problem, I can just use MRIcron instead. Would it be possible to change the tag of the orignal image (before 4 days ago) so I can maybe pull by that tag and use the version which worked for me? At the moment all of the images have the tag _latest_ .
 Very sorry for the hassle, just trying to make the most out of the software and we have a ton of clinical data to inspect, hence using the college's RCS! Thank you (:

**Comment by plwp** [comment]
Sorry, that was a typo in the Dockerfile. Fixed and have also tagged the update as :fix26.

**Comment by hajerkr** [comment]
Hi Pat @plwp thanks for the update. There might be an issue still, the volume mounting seems to be failing, just on vistarsier:latest and vistarsier:26fix (`unable to locate the following file`  error) but I don't get that error with pytarsier. I gave up on trying to run it on singularity with the new fixes, so I am using my own windows machine right now.

![image](https://user-images.githubusercontent.com/13291010/127531997-f02059b8-4cdb-4b69-a5d3-aac93d16b350.png)

Let me know if you believe it's an issue on my end, but it could be the build/Dockerfile again?
